---
# tasks file for users
- name: Remove user "{{username}}" if exists (with suppression of errors)
  shell: userdel -r "{{username}}" 2> /dev/null
  #command userdel -r "{{username}}"
  ignore_errors: true

- name: Create user "{{username}}" w password as a string
  user:
    name: "{{username}}"
    state: present
    password: "{{ password | string | password_hash('sha512') }}"
    shell: /bin/bash
    #group: "{{ admin_group }}"

- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key }}"
    mode: 0700
    owner: "{{ username }}"
    state: directory

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
    owner: "{{ username }}"

- name: Add
  lineinfile:
    dest: "{{ dest_key }}/authorized_keys"
    line: "{{lookup('file', '~/.ssh/id_rsa_ansible_2.pub')}}"
    create: yes
