version: "3.3"
services:
  php:
    build: .
    ports:
      - "${HOST}:${PHP_PORT}:${PHP_PORT}"
    depends_on:
      - nginx
    volumes:
      - ./www:${ROOT}
    networks:
      - net
    healthcheck:
      test: curl --fail --silent http://nginx:${WEB_PORT_INTERNAL} | grep works || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: "nginx:1.21.6-alpine"
    ports:
      - "${HOST}:${WEB_PORT_EXTERNAL}:${WEB_PORT_INTERNAL}"
    volumes:
      - ./www:${ROOT}
      - ./nginx/dev.conf:/etc/nginx/conf.d/site.template
    env_file:
      - .env
    command: /bin/sh -c "envsubst '$$WEB_PORT_INTERNAL $$PHP_PORT $$HOST $$ROOT' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default2.conf && nginx -g 'daemon off;'"
    networks:
      - net

networks:
  net:
