# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.env.enable # Enable vagrant-env(.env)
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.host_name = "postgresql"

  config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
  config.vm.provision :shell,
    :path => "Vagrant-setup/bootstrap.sh",
    env: {
        "DB_PORT_HOST" => ENV['DB_PORT_HOST'],
        "DB_NAME" => ENV['DB_NAME'],
        "DB_USER" => ENV['DB_USER'],
        "DB_PASSWORD" => ENV['DB_PASSWORD'],
        "PG_VERSION" => ENV['PG_VERSION']
      }

  # PostgreSQL Server port forwarding (Container - Host)
  config.vm.forward_port ENV['DB_PORT_INT'], ENV['DB_PORT_HOST']
end
