---
# tasks file for php
- name: Install PHP-FPM
  apt:
    pkg:
      - php{{php_ver}}-fpm
    state: latest
  register: phpinstalled # register statement for successfull installing for PHP-FPM

- name: Ensure what we use TCP port for listening
  when: phpinstalled.stdout.find('is not installed') == -1
  lineinfile:
    path: /etc/php/{{php_ver}}/fpm/pool.d/www.conf
    regexp: "^listen ="
    line: "listen = {{php_server}}:{{php_port}}"

- name: Set allowed clients for listening for PHP-FPM
  lineinfile:
    path: /etc/php/{{php_ver}}/fpm/pool.d/www.conf
    regexp: "^;listen.allowed_clients ="
    line: "listen.allowed_clients = {{web_server}}"

- name: Create Web Root
  file: path={{ document_root }}  mode=775 state=directory #owner=nginx group=nginx

- name: Creating an index.php file with content
  copy:
    dest: "{{document_root}}/index.php"
    content: |
      <?php phpinfo();?>