---
- hosts: test # ansible
  gather_facts: no
  become: yes

  roles:
  - dnsmasq
  - { role: webserver, become: yes }
  vars:
    group: superusers
    default_user_password: 1234
    users: [ user2, user3 ]

  tasks:
  - name: Create group
    group:
      name: "{{ group }}"
      state: present

  - name: Create Users Task
    user:
      name: "{{ item }}"
      state: present
      password: "{{ default_user_password  | string | password_hash('sha512','A512') }}"
      shell: /bin/bash
      group: "{{ group }}"
    with_items:
      - "{{ users }}"

  - name: Allow '{{ group }}' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%{{ group }}'
      line: '%{{ group }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
