---
- hosts: ansible
  gather_facts: false
  remote_user: admin
  become: true
  vars:
    ansible_ssh_private_key_file: "/home/qshar/.ssh/key_auth_github"
  tasks:
    - name: apt update
      apt:
        update_cache: yes
      tags: init

    - name: Install postfix and packages
      apt:
        pkg:
        - postfix
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
      tags: init

    - name: Start up the postfix service
      service:
        name: postfix
        state: started
        enabled: true
      tags: init

    - name: Uninstall postfix and its dependensies
      apt:
        pkg:
        - postfix
        state: absent
        purge: yes
        autoremove: yes
      tags: drop