# ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa_ansible_2
# ansible-vault encrypt ~/.ssh/id_rsa_ansible_2 --output ~/ANSIBLE/vault_id_rsa_ansible_2
# ansible-vault create vault
# Run this command using "--ask-vault-pass" option to decrypt your vault file (see ansible-vault for info on how to manage an encrypted vault).
---
- hosts: "{{ host_alias }}"
  remote_user: "{{ cloud_sa_user }}" # sa-user in the remote (cloud) host
  gather_facts: false
  vars_files:
    - vault # protected variables
    - vars # public variables
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ host_ssh }}" # access to remote host
    source_key: "{{ source_key }}"
    dest_key: /home/{{username}}/.ssh
  tasks:
    - name: Debug info
      vars:
          msg: |
            username: {{ username }}
            password: {{ password }}
            dest_key = {{ dest_key }}
            source_key = {{ source_key }}
            host_ssh = {{ host_ssh }}
      debug:
        msg: "{{ msg | trim | split('\n') }}"
      tags: debug

    - name: Remove user "{{username}}" if exists (with suppression of errors)
      become: yes
      shell: userdel -r "{{username}}" 2> /dev/null
      #command userdel -r "{{username}}"
      ignore_errors: yes
      tags: clear

    - name: Create user "{{username}}" w password as a string
      user:
        name: "{{username}}"
        state: present
        password: "{{ password | string | password_hash('sha512') }}"
        shell: /bin/bash
        #group: "{{ admin_group }}"

    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key }}"
        mode: 0700
        owner: "{{ username }}"
        state: directory

    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
        owner: "{{ username }}"

    - name: Rename the received SSH key as needed
      shell: cd "{{ dest_key }}" && mv {{source_key}} id_rsa

    - name: Change owner for the renamed file
      file:
        path: "{{ dest_key }}/id_rsa"
        mode: 0600
        owner: "{{ username }}"

    - name: Add SSH key to authorized keys
      lineinfile:
        dest: "{{ dest_key }}/authorized_keys"
        line: "{{lookup('file', '/home/qshar/.ssh/id_rsa_ansible_2.pub')}}"
        create: yes
